name: build-image
run-name: Build the shimboot disk image for all boards
on: [push]

jobs:
  build:
    permissions:
      contents: write

    strategy: 
      matrix:
        board: [dedede, octopus]

    runs-on: ubuntu-latest
    steps:

      - name: download repo
        uses: actions/checkout@v4
      
      - name: download
        run: |
              wget -O ${{ matrix.board }}.zip https://dl.darkn.bio/api/raw/?path=/SH1mmer/${{ matrix.board }}.zip
              

      - name: upload img
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.board }}
          path: ${{ matrix.board }}.zip
          compression-level: 7
  
      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: ${{ matrix.board }}.zip
