name: build-image
run-name: Build the shimboot disk image for all boards
on: [push]

jobs:
  build:
    permissions:
      contents: write

    strategy: 
      matrix:
        board: [dedede, octopus]

    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: download repo
        uses: actions/checkout@v4
      
      - name: download
        run: |
              git config rebase.true
              git pull
              echo "Downloading ${{ matrix.board }} shim image" > status.txt
              git add .
              git config user.name "Timothy Heironimus"
              git config user.email "timothyheironimus6+github@gmail.com"
              git commit -m "downloading shim image ${{ matrix.board }}"
              git push --force
              wget https://dl.darkn.bio/api/raw/?path=/SH1mmer/${{ matrix.board }}.zip
              git add .
              git config user.name "Timothy Heironimus"
              git config user.email "timothyheironimus6+github@gmail.com"
              git commit -m "downloaded shim image ${{ matrix.board }}"
              

      - name: upload img
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.board }}
          path: ${{ matrix.board }}.zip
          compression-level: 7
  
      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: ${{ matrix.board }}.zip
